apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bazarr.fullname" . }}
  labels:
    {{- include "bazarr.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.bazarr.replicaCount }}
  selector:
    matchLabels:
      {{- include "bazarr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.bazarr.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bazarr.labels" . | nindent 8 }}
        {{- with .Values.bazarr.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.bazarr.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bazarr.serviceAccountName" . }}
      securityContext:
      {{- toYaml .Values.bazarr.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.bazarr.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.bazarr.securityContext | nindent 12 }}
          image: "{{ .Values.bazarr.image.repository }}:{{ .Values.bazarr.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.bazarr.image.pullPolicy }}
          {{- with .Values.bazarr.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.bazarr.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.bazarr.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.bazarr.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.bazarr.resources | nindent 12 }}
          {{- with .Values.bazarr.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.bazarr.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bazarr.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bazarr.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bazarr.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
