apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qbittorrent.fullname" . }}
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.qbittorrent.replicaCount }}
  selector:
    matchLabels:
      {{- include "qbittorrent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.qbittorrent.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "qbittorrent.labels" . | nindent 8 }}
        {{- with .Values.qbittorrent.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.qbittorrent.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "qbittorrent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.qbittorrent.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.qbittorrent.securityContext | nindent 12 }}
          image: "{{ .Values.qbittorrent.image.repository }}:{{ .Values.qbittorrent.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.qbittorrent.image.pullPolicy }}
          {{- with .Values.qbittorrent.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.qbittorrent.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            {{- toYaml .Values.qbittorrent.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.qbittorrent.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.qbittorrent.resources | nindent 12 }}
          {{- with .Values.qbittorrent.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.qbittorrent.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.qbittorrent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.qbittorrent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.qbittorrent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
