allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    defaultVolumeType: hostPath
    meta.helm.sh/release-name: local-path-provisioner
    meta.helm.sh/release-namespace: local-path-provisioner
    storageclass.kubernetes.io/is-default-class: "false"
  labels:
    app.kubernetes.io/instance: local-path-provisioner
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: local-path-provisioner
    app.kubernetes.io/version: v0.0.31
    helm.sh/chart: local-path-provisioner-0.0.31
  name: local-path-retain
provisioner: cluster.local/local-path-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
