apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jellyfin.fullname" . }}
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.jellyfin.replicaCount }}
  selector:
    matchLabels:
      {{- include "jellyfin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.jellyfin.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jellyfin.labels" . | nindent 8 }}
        {{- with .Values.jellyfin.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.jellyfin.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jellyfin.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.jellyfin.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.jellyfin.securityContext | nindent 12 }}
          image: "{{ .Values.jellyfin.image.repository }}:{{ .Values.jellyfin.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.jellyfin.image.pullPolicy }}
          {{- with .Values.jellyfin.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.jellyfin.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.jellyfin.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.jellyfin.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.jellyfin.resources | nindent 12 }}
          {{- with .Values.jellyfin.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.jellyfin.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jellyfin.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jellyfin.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jellyfin.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
